Win/Controllers/PerfilController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Win.Interfaces.Services;
using Win.Models;

namespace Win.Controllers
{
    [Authorize]
    public class PerfilController: Controller
    {
        private IPostService _postService;

        public PerfilController(IPostService postService)
        {
            _postService = postService;
        }


        public IActionResult Index()
        {
            return View();
        }
    }
}

Win/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Win</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/custom.css" rel="stylesheet" />
        <link href="~/lib/ladda-bootstrap-master/dist/ladda-themeless.min.css" rel="stylesheet" />
        <link href="~/lib/toastr-master/build/toastr.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">



    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link href="~/lib/ladda-bootstrap-master/dist/ladda-themeless.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="padding-top:70px; background-color: #eee">
    <nav class="navbar navbar-default navbar-fixed-top" id="menu">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Win</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Perfil" asp-action="Index">Meu Perfil</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

        <div class="clearfix"></div>

    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="~/lib/ladda-bootstrap-master/dist/spin.min.js"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/ladda.min.js"></script>
        <script src="~/lib/ckeditor/ckeditor.js"></script>
        <script src="~/lib/toastr-master/build/toastr.min.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/ladda.min.js"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/spin.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Win/Views/Shared/_Perfil.cshtml
@inject UserManager<ApplicationUser> UserManager


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Win</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/custom.css" rel="stylesheet" />
        <link href="~/lib/ladda-bootstrap-master/dist/ladda-themeless.min.css" rel="stylesheet" />
        <link href="~/lib/toastr-master/build/toastr.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">



    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

        <link href="~/lib/ladda-bootstrap-master/dist/ladda-themeless.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="padding-top:50px; background-color: #eee">
    <nav class="navbar navbar-default navbar-fixed-top" id="menu" style="border: none;margin-bottom:-20px">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Win</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Perfil" asp-action="Index">Meu Perfil</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="text-center" style="background-color: #3ca2e0; color: #fff;padding: 70px">

        @if(UserManager.GetUserAsync(User).Result.ImagemPerfil.Where(i => i.ApplicationUserId == UserManager.GetUserAsync(User).Result.Id).OrderBy(c=> c.DataUpload).Select(c => c.NomeImagem) != null)
        {

            <img id="img-perfil" src="/uploads/imagens/perfil/@UserManager.GetUserAsync(User).Result.ImagemPerfil.Where(i => i.ApplicationUserId == UserManager.GetUserAsync(User).Result.Id).OrderBy(c=> c.DataUpload).Select(c => c.NomeImagem)" class="tim" />

        }
        else
        {

            <img id="img-perfil" class="tim" src="https://png.icons8.com/ios/150/000000/user-male-circle-filled.png" alt="Alternate Text" />

        }
        <h4>@UserManager.GetUserAsync(User).Result.Nome</h4>
    </div>




    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <script src="~/lib/ladda-bootstrap-master/dist/spin.min.js"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/ladda.min.js"></script>
        <script src="~/lib/ckeditor/ckeditor.js"></script>
        <script src="~/lib/toastr-master/build/toastr.min.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/ladda.min.js"></script>
        <script src="~/lib/ladda-bootstrap-master/dist/spin.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>